# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - data: mp20_only  # joint / qm9_only / mp20_only
  - encoder: transformer
  - decoder: transformer
  - autoencoder_module: vae
  - callbacks: autoencoder_default  # autoencoder_default / _qm9_only / _mp20_only
  - logger: null # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - _self_

# run name, eg. for wandb logging
name: ""

# task name, determines output directory path
task_name: "train_autoencoder"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["joint", "autoencoder", "train"]

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: 9
